# Generated by Django 6.0 on 2025-12-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao_comprador', models.CharField(max_length=255)),
                ('numero_pedido', models.CharField(max_length=50)),
                ('produto', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pedido', models.DateField()),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['data_pedido'],
            },
        ),
    ]
