# Generated by Django 6.0 on 2025-12-26 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='numero_pedido',
            new_name='numero_pregao',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='orgao_comprador',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_empenho',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='orgao',
            field=models.CharField(default='LEGADO', max_length=255, verbose_name='Órgão Comprador'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('unidade', models.CharField(max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['numero_item'],
                'unique_together': {('pedido', 'numero_item')},
            },
        ),
    ]
