# Generated by Django 6.0 on 2025-12-21 19:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=50)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['sigla'],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='bloqueado',
            field=models.BooleanField(default=False, verbose_name='Orçamento Bloqueado'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='prazo_entrega',
            field=models.CharField(default='A Combinar', max_length=100, verbose_name='Prazo de Entrega'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='validade_dias',
            field=models.IntegerField(default=15, verbose_name='Validade (dias)'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cor',
            field=models.CharField(blank=True, default='#2563eb', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Unitário'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('pedido', 'Pedido Gerado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orcamentos.unidademedida', verbose_name='Unidade'),
        ),
    ]
