# Generated by Django 6.0 on 2025-12-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_unidademedida_empresa_cnpj_empresa_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo da Empresa'),
        ),
    ]
